export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';

export const ROLE_MODEL = 'ROLE_MODEL';
export const USER_ROLE_RELATION_MODEL = 'USER_ROLE_RELATION_MODEL';
export const USER_MODEL = 'USER_MODEL';

export const ROLES_SERVICE = 'ROLES_SERVICE';
export const USER_ROLE_RELATION_SERVICE = 'USER_ROLE_RELATION_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';

export const AUTHENTICATE = 'AUTHENTICATE';
